/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Draft {
  author_handle: string;
  author_id: string;
  content: Json;
  time_most_recently_edited: Timestamp;
}

export interface Like {
  liker_id: string;
  post_id: string;
  timestamp: Timestamp | null;
}

export interface Post {
  author_display_name: string;
  author_handle: string;
  author_id: string;
  content: Json;
  id: Generated<string>;
  replies: string[] | null;
  time_created: Timestamp;
}

export interface Repost {
  post_id: string;
  reposter_id: string;
  timestamp: Timestamp | null;
}

export interface DB {
  draft: Draft;
  like: Like;
  post: Post;
  repost: Repost;
}
