/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Draft {
  author_handle: string;
  author_id: string;
  content: Json;
  times_edited: ArrayType<Timestamp>;
}

export interface Post {
  author_display_name: string | null;
  author_handle: string | null;
  author_id: string | null;
  content: Json | null;
  id: string;
  index_in_thread: number | null;
  liked_by: string[] | null;
  posts_in_thread: string[] | null;
  replies: string[] | null;
  reposted_by: string[] | null;
  time_created: Timestamp | null;
}

export interface DB {
  draft: Draft;
  post: Post;
}
